### ISSUE TITLE
Tracking JSoC 2019

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqOperators.jl#109]
- [x] Boundary condition redo and 1D operator correctness https://github.com/JuliaDiffEq/DiffEqOperators.jl/issues/98
- [ ] Integration tests of the full 1D operators + boundary condition handling on some PDEs
- [ ] Integrate the non-uniform grid operator into the new version
- [ ] Update the upwinding operators to use this new form. 
- [ ] Give the boundary operators an optional direction vector
- [x] Setup `update_coefficients!` to update the direction vector based on a given direction function
- [ ] Higher dimensional operators
- [ ] Composed operators (a type of holding `L*Q`, then expand to `L1*Q1 + L2*Q2`)
- [ ] Higher dimensional composed operator specializations (NNLib.jl)
- [ ] Higher dimensional boundary condition padding

**Comment by xtalax** [comment]
Could someone elaborate on this direction vector? Is this directional as in upwind/downwind, forward or backward diff, or dimension?

**Comment by shivin9** [comment]
It is directional as in upwind/downwind operators. That will naturally affect the direction of differentiation stencil also.
