### ISSUE TITLE
Roadmap for Vector Derivative Operators

### ISSUE THREAD

**Issue by xtalax** [JuliaDiffEq/DiffEqOperators.jl#153]
# Roadmap for Vector Derivative Operators
Continuing from #146 

A checklist on how to allow Vector calculus operations on `u::AbstractArray{AbstractArray{T,M}, N}`, useful in a lot of physics applications and likely elsewhere.

This is just spitballing to get some ideas that have been floating about written down before I forget them - This would be a fair amount of work, especially writing a mul that can handle arbitrary vector operators efficiently. I'd appreciate feedback and ideas @ChrisRackauckas @ajozefiak @shivin9, especially on which option (listed below) is preferable.

## Option 1: extend `DerivativeOperator`
- [ ] Relax constraint on `DerivativeOperator{T<:Real, etc.}` to allow T to be an `AbstractArray`
- [ ] Give `DerivativeOperator` a boolean type parameter `Vec`, that determines whether it acts on a specific component of `u`, or the whole `T` at once.
- [ ] Give `DerivativeOperator` a field, say `component` that contains `Vec ? (NTuple{Int} **OR** CartesianIndex) : Nothing`, specifying the index of the component of `u` to operate on, to abuse julia notation `L*u = L*u[:][component]`

## Option 2: create a `VectorDerivativeOperator` that wraps a `A::DerivativeOperator` 
- [ ] Create `VectorDerivativeOperator`  - only needs fields for `A` and `component`
- [ ] Implement all other methods to get this to behave as an `AbstractDiffEqLinearOperator`

## In both cases
- [ ] Specialised `*`, `mul` `ldiv` convolutions etc. that account for the components
- [ ] A `ComposedVectorOperator`, with `ops::Array{O<:AbstractCompositeOperator, N}` which is an array with the same shape as the return eltype of the operator (may be different from the shape of the `eltype` of `u`). Each element of ops is a composed `DiffEqOperator`,  which alone would act on some `u` to give a scalar field.
- [ ] Finally, and critically, a highly optimised `mul` for the `ComposedVectorOperator` that can query the `ops` and fuse at least `for I in CartesianIndices(u_interior)` in the convolutions.

**Comment by ChrisRackauckas** [comment]
I don't get why it would be a `DerivativeOperator`. Almost none of the functions would apply. It should be its own operator.
